language: node_js

node_js:
- 8

cache:
  directories:
    - node_modules

script:
  - npm test

notifications:
  email: false

before_deploy:
  - npm run build && cp -r dist/* .

deploy:
  local_dir: /
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
