language: node_js

node_js:
- 6

cache:
  directories:
    - node_modules

script:
  - npm lint

notifications:
  email: false

before_deploy:
  - npm run build && cp -r dist/* demo/

deploy:
  local_dir: demo
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
